version: '3'
services:
  slimevr-database:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: slimevr
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: slimevr
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - database-volume:/var/lib/postgresql/data
    networks:
      - slimevr-network
  slimevr-api:
    build:
      context: .
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - 3000:3000
    depends_on:
      - slimevr-database
      - slimevr-api-s3
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    networks:
      - slimevr-network
      - caddy-network
    secrets:
      - access_key
      - secret_key
    environment:
      APP_ENV: ${APP_ENV}
      LISTEN_HOST: ${LISTEN_HOST}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUILDS_BUCKET: ${S3_BUILDS_BUCKET}
      GITHUB_AUTH: ${GITHUB_AUTH}
  slimevr-api-s3:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9099:9099
    volumes:
      - storage-minio:/data
    secrets:
      - access_key
      - secret_key
    command: server --address ":9099" --console-address ":9000" /data/disk{1...4}
    restart: always
    networks:
      - slimevr-network
      - caddy-network
  slimevr-api-s3-init:
    image: minio/mc
    depends_on:
      - slimevr-api-s3
    networks:
      - slimevr-network
    secrets:
      - access_key
      - secret_key
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set slimevr http://slimevr-api-s3:9099 `cat /run/secrets/access_key` `cat /run/secrets/secret_key`;
      /usr/bin/mc mb slimevr/slimevr-firmware-builds;
      /usr/bin/mc policy set public slimevr/slimevr-firmware-builds;
      exit 0;
      "

volumes:
  database-volume:
  storage-minio:
    external: false

secrets:
  access_key:
    file: ./docker/minio/access_key.txt
  secret_key:
    file: ./docker/minio/secret_key.txt

networks:
  slimevr-network:
  caddy-network:
    external: true